### ISSUE TITLE
Add master branch 

### ISSUE THREAD

**Issue by Va5kez** [sulavalley/website#6]
- Create master branch
- Exclude tests in master branch

**Comment by RDRR7** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Agregar CI/CD al Proyecto](https://trello.com/c/WNtYIr9f/5-agregar-ci-cd-al-proyecto)

**Comment by andresrgz** [comment]
@RDRR7 I created the `master` branch and disabled status checking for it. Anything else that must be configured before closing this issue?

**Comment by RDRR7** [comment]
@astrothing status check shouldn't be disabled, this allows merge without passing tests, instead it will be disabled through CircleCi so it doesn't run tests again in `master` branch.
